# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 2.0.1

    You can manually edit this file.
"""  # noqa: E501



pytest_plugins = [
    # Add your or generated fixtures here from framework.fixtures
    "framework.fixtures.http.petstore_service",
]