# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 1.0.0

    You can manually edit this file.
"""  # noqa: E501


"""
    Need for auto registration fixtures, you can append more fixtures to this list.

    Example:
        pytest_plugins = get_fixtures()
        pytest_plugins += ["fixture1", "fixture2"]
"""  # noqa: E501

import framework.fixtures  # noqa: F401
from e2efast.fixture_registry import get_fixtures

pytest_plugins = get_fixtures()