# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: fixtures.base
    version: 2.0.1

    You can manually edit this file.
"""  # noqa: E501

from functools import partial

import httpx

"""
You can redefine client class for own needs, client should be a subclass of httpx.Client

Example:
    from httpx import AsyncClient
    ClientClass = AsyncClient
"""

ClientClass = partial(httpx.Client, timeout=httpx.Timeout(60.0))
