# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 2.0.1

    Do not edit the class manually.
"""  # noqa: E501

import os

import pytest

from framework.fixtures.http.base import ClientClass
from framework.clients.http.petstore.pet_client import PetClient
from framework.clients.http.petstore.store_client import StoreClient
from framework.clients.http.petstore.user_client import UserClient


class PetstoreService:
    def __init__(self, api_client: ClientClass) -> None:
        self.api_client = api_client
        self.pet = PetClient(api_client=api_client)
        self.store = StoreClient(api_client=api_client)
        self.user = UserClient(api_client=api_client)


@pytest.fixture(scope="session")
def petstore_service_client() -> ClientClass:
    return ClientClass(base_url=os.getenv("PETSTORE_BASE_URL"))


@pytest.fixture(scope="session")
def petstore_service(petstore_service_client: ClientClass) -> PetstoreService:
    return PetstoreService(api_client=petstore_service_client)
