# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 1.0.0

    Do not edit the class manually.
"""  # noqa: E501

from typing import TypeVar

import httpx

import pytest


from framework.clients.http.petstore.pet_client import PetClient
from framework.clients.http.petstore.store_client import StoreClient
from framework.clients.http.petstore.user_client import UserClient

from framework.fixtures.http.base import ClientClass
from framework.settings.base_settings import Settings
from e2efast.fixture_registry import register_fixture

ClientType = TypeVar("ClientType", bound=httpx.Client)


class PetstoreService:
    def __init__(self, api_client: ClientType) -> None:
        self.api_client = api_client
        self.pet = PetClient(api_client=api_client)
        self.store = StoreClient(api_client=api_client)
        self.user = UserClient(api_client=api_client)


@pytest.fixture(scope="session")
def petstore_service_client() -> ClientType:
    client = ClientClass()
    client.base_url = Settings().petstore
    return client


@pytest.fixture(scope="session")
def petstore_service(petstore_service_client: ClientType) -> PetstoreService:
    return PetstoreService(api_client=petstore_service_client)


register_fixture(__name__)
