# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 0.3.0

    You can manually edit this file.
"""  # noqa: E501



from pydantic_settings import BaseSettings
from pydantic import Field


class Settings(BaseSettings):
    """Environment-driven configuration for HTTP clients."""

    petstore: str | None = Field(
        default="https://petstore3.swagger.io/api/v3",
        alias="PETSTORE_BASE_URL",
        description="Base URL for the service",
    )


__all__ = ["Settings"]