# coding: utf-8
"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: petstore
    version: 2.0.1

    Do not edit the class manually.
"""  # noqa: E501

from httpx import Response
from typing import Any

from httpx import Client


from internal.clients.http.petstore.models.api_models import (
    
    FindPetsByTagsResponse200,
    
    UploadFileRequestBody,
    
    FindPetsByStatusResponse200,
    
    ApiResponse,
    
    Pet,
    
)



class PetApi:

    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def put_pet(
        self,
        pet: Pet, # noqa: E501
        **kwargs: Any,
    ) -> Pet:
        """
        Update an existing pet..

        Args:
            pet(Pet): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Pet: ...
        """  # noqa: D205,E501

        response =self.put_pet_with_http_info(
            pet=pet, # noqa: E501
            **kwargs,
        )
        return Pet.model_validate_json(response.text)


    def put_pet_with_http_info(
        self,
        pet: Pet, # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        Update an existing pet..

        Args:
            pet(Pet): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})
        
        content = pet.model_dump_json(exclude_none=True, by_alias=True) # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.put(
            url=f"/pet",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def post_pet(
        self,
        pet: Pet, # noqa: E501
        **kwargs: Any,
    ) -> Pet:
        """
        Add a new pet to the store..

        Args:
            pet(Pet): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Pet: ...
        """  # noqa: D205,E501

        response =self.post_pet_with_http_info(
            pet=pet, # noqa: E501
            **kwargs,
        )
        return Pet.model_validate_json(response.text)


    def post_pet_with_http_info(
        self,
        pet: Pet, # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        Add a new pet to the store..

        Args:
            pet(Pet): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})
        
        content = pet.model_dump_json(exclude_none=True, by_alias=True) # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url=f"/pet",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def get_pet_find_by_status(
        self,
        status: str,
        **kwargs: Any,
    ) -> FindPetsByStatusResponse200:
        """
        Finds Pets by status..

        Args:
            status(str, required): Status values that need to be considered for
filter
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            FindPetsByStatusResponse200: ...
        """  # noqa: D205,E501

        response =self.get_pet_find_by_status_with_http_info(
            status=status,
            **kwargs,
        )
        return FindPetsByStatusResponse200.model_validate_json(response.text)


    def get_pet_find_by_status_with_http_info(
        self,
        status: str,
        **kwargs: Any,
    ) -> Response:
        """
        Finds Pets by status..

        Args:
            status(str, required): Status values that need to be considered for
filter
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        # process the query parameters
        params_map = {
            "status": status,
        }
        params = {k: v for k, v in params_map.items() if v}
        headers = kwargs.pop("headers", {})
        
        response = self.api_client.get(
            url=f"/pet/findByStatus",
            params=params,
            headers=headers,
            **kwargs,
        )
        return response

    def get_pet_find_by_tags(
        self,
        tags: list,
        **kwargs: Any,
    ) -> FindPetsByTagsResponse200:
        """
        Finds Pets by tags..

        Args:
            tags(list, required): Tags to filter by
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            FindPetsByTagsResponse200: ...
        """  # noqa: D205,E501

        response =self.get_pet_find_by_tags_with_http_info(
            tags=tags,
            **kwargs,
        )
        return FindPetsByTagsResponse200.model_validate_json(response.text)


    def get_pet_find_by_tags_with_http_info(
        self,
        tags: list,
        **kwargs: Any,
    ) -> Response:
        """
        Finds Pets by tags..

        Args:
            tags(list, required): Tags to filter by
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        # process the query parameters
        params_map = {
            "tags": tags,
        }
        params = {k: v for k, v in params_map.items() if v}
        headers = kwargs.pop("headers", {})
        
        response = self.api_client.get(
            url=f"/pet/findByTags",
            params=params,
            headers=headers,
            **kwargs,
        )
        return response

    def get_pet_pet_id(
        self,
        pet_id: int,
        **kwargs: Any,
    ) -> Pet:
        """
        Find pet by ID..

        Args:
            pet_id(int, required): ID of pet to return
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Pet: ...
        """  # noqa: D205,E501

        response =self.get_pet_pet_id_with_http_info(
            pet_id=pet_id,
            **kwargs,
        )
        return Pet.model_validate_json(response.text)


    def get_pet_pet_id_with_http_info(
        self,
        pet_id: int,
        **kwargs: Any,
    ) -> Response:
        """
        Find pet by ID..

        Args:
            pet_id(int, required): ID of pet to return
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})
        
        response = self.api_client.get(
            url=f"/pet/{pet_id}",
            headers=headers,
            **kwargs,
        )
        return response

    def post_pet_pet_id(
        self,
        pet_id: int,
        name: str | None = None,
        status: str | None = None,
        **kwargs: Any,
    ) -> Pet:
        """
        Updates a pet in the store with form data..

        Args:
            pet_id(int, required): ID of pet that needs to be updated
            name(str | None, optional): Name of pet that needs to be updated
            status(str | None, optional): Status of pet that needs to be updated
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Pet: ...
        """  # noqa: D205,E501

        response =self.post_pet_pet_id_with_http_info(
            pet_id=pet_id,
            name=name,
            status=status,
            **kwargs,
        )
        return Pet.model_validate_json(response.text)


    def post_pet_pet_id_with_http_info(
        self,
        pet_id: int,
        name: str | None = None,
        status: str | None = None,
        **kwargs: Any,
    ) -> Response:
        """
        Updates a pet in the store with form data..

        Args:
            pet_id(int, required): ID of pet that needs to be updated
            name(str, optional): Name of pet that needs to be updated
            status(str, optional): Status of pet that needs to be updated
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        # process the query parameters
        params_map = {
            "name": name,
            "status": status,
        }
        params = {k: v for k, v in params_map.items() if v}
        headers = kwargs.pop("headers", {})
        
        response = self.api_client.post(
            url=f"/pet/{pet_id}",
            params=params,
            headers=headers,
            **kwargs,
        )
        return response

    def delete_pet_pet_id(
        self,
        pet_id: int,
        api_key: str | None = None,
        **kwargs: Any,
    ) -> Response:
        """
        Deletes a pet..

        Args:
            pet_id(int, required): Pet id to delete
            api_key(str | None, optional): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: D205,E501

        response =self.delete_pet_pet_id_with_http_info(
            pet_id=pet_id,
            api_key=api_key,
            **kwargs,
        )
        return response


    def delete_pet_pet_id_with_http_info(
        self,
        pet_id: int,
        api_key: str | None = None,
        **kwargs: Any,
    ) -> Response:
        """
        Deletes a pet..

        Args:
            pet_id(int, required): Pet id to delete
            api_key(str, optional): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        # process the header parameters
        headers_map = {
            "api_key": str(api_key),
        }
        headers = {k: str(v) for k, v in headers_map.items() if v}
        headers.update(kwargs.pop("headers", {}))
        
        response = self.api_client.delete(
            url=f"/pet/{pet_id}",
            headers=headers,
            **kwargs,
        )
        return response

    def post_pet_pet_id_upload_image(
        self,
        upload_file_request_body: UploadFileRequestBody, # noqa: E501
        pet_id: int,
        additional_metadata: str | None = None,
        **kwargs: Any,
    ) -> ApiResponse:
        """
        Uploads an image..

        Args:
            upload_file_request_body(UploadFileRequestBody): ...
            pet_id(int, required): ID of pet to update
            additional_metadata(str | None, optional): Additional Metadata
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            ApiResponse: ...
        """  # noqa: D205,E501

        response =self.post_pet_pet_id_upload_image_with_http_info(
            pet_id=pet_id,
            upload_file_request_body=upload_file_request_body, # noqa: E501
            additional_metadata=additional_metadata,
            **kwargs,
        )
        return ApiResponse.model_validate_json(response.text)


    def post_pet_pet_id_upload_image_with_http_info(
        self,
        upload_file_request_body: UploadFileRequestBody, # noqa: E501
        pet_id: int,
        additional_metadata: str | None = None,
        **kwargs: Any,
    ) -> Response:
        """
        Uploads an image..

        Args:
            upload_file_request_body(UploadFileRequestBody): ...
            pet_id(int, required): ID of pet to update
            additional_metadata(str, optional): Additional Metadata
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        # process the query parameters
        params_map = {
            "additionalMetadata": additional_metadata,
        }
        params = {k: v for k, v in params_map.items() if v}
        headers = kwargs.pop("headers", {})
        
        content = upload_file_request_body.model_dump_json(exclude_none=True, by_alias=True) # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url=f"/pet/{pet_id}/uploadImage",
            content=content,
            params=params,
            headers=headers,
            **kwargs,
        )
        return response