# coding: utf-8
"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: petstore
    version: 2.0.1

    Do not edit the class manually.
"""  # noqa: E501

from httpx import Response
from typing import Any

from httpx import Client


from internal.clients.http.petstore.models.api_models import (
    
    LoginUserResponse200,
    
    CreateUsersWithListInputRequestBody,
    
    User,
    
)



class UserApi:

    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def post_user(
        self,
        user: User, # noqa: E501
        **kwargs: Any,
    ) -> User:
        """
        Create user..

        Args:
            user(User): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            User: ...
        """  # noqa: D205,E501

        response =self.post_user_with_http_info(
            user=user, # noqa: E501
            **kwargs,
        )
        return User.model_validate_json(response.text)


    def post_user_with_http_info(
        self,
        user: User, # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        Create user..

        Args:
            user(User): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})
        
        content = user.model_dump_json(exclude_none=True, by_alias=True) # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url=f"/user",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def post_user_create_with_list(
        self,
        create_users_with_list_input_request_body: CreateUsersWithListInputRequestBody, # noqa: E501
        **kwargs: Any,
    ) -> User:
        """
        Creates list of users with given input array..

        Args:
            create_users_with_list_input_request_body(CreateUsersWithListInputRequestBody): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            User: ...
        """  # noqa: D205,E501

        response =self.post_user_create_with_list_with_http_info(
            create_users_with_list_input_request_body=create_users_with_list_input_request_body, # noqa: E501
            **kwargs,
        )
        return User.model_validate_json(response.text)


    def post_user_create_with_list_with_http_info(
        self,
        create_users_with_list_input_request_body: CreateUsersWithListInputRequestBody, # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        Creates list of users with given input array..

        Args:
            create_users_with_list_input_request_body(CreateUsersWithListInputRequestBody): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})
        
        content = create_users_with_list_input_request_body.model_dump_json(exclude_none=True, by_alias=True) # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url=f"/user/createWithList",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def get_user_login(
        self,
        username: str | None = None,
        password: str | None = None,
        **kwargs: Any,
    ) -> LoginUserResponse200:
        """
        Logs user into the system..

        Args:
            username(str | None, optional): The user name for login
            password(str | None, optional): The password for login in clear text
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            LoginUserResponse200: ...
        """  # noqa: D205,E501

        response =self.get_user_login_with_http_info(
            username=username,
            password=password,
            **kwargs,
        )
        return LoginUserResponse200.model_validate_json(response.text)


    def get_user_login_with_http_info(
        self,
        username: str | None = None,
        password: str | None = None,
        **kwargs: Any,
    ) -> Response:
        """
        Logs user into the system..

        Args:
            username(str, optional): The user name for login
            password(str, optional): The password for login in clear text
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        # process the query parameters
        params_map = {
            "username": username,
            "password": password,
        }
        params = {k: v for k, v in params_map.items() if v}
        headers = kwargs.pop("headers", {})
        
        response = self.api_client.get(
            url=f"/user/login",
            params=params,
            headers=headers,
            **kwargs,
        )
        return response

    def get_user_logout(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        Logs out current logged in user session..

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: D205,E501

        response =self.get_user_logout_with_http_info(
            **kwargs,
        )
        return response


    def get_user_logout_with_http_info(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        Logs out current logged in user session..

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})
        
        response = self.api_client.get(
            url=f"/user/logout",
            headers=headers,
            **kwargs,
        )
        return response

    def get_user_username(
        self,
        username: str,
        **kwargs: Any,
    ) -> User:
        """
        Get user by user name..

        Args:
            username(str, required): The name that needs to be fetched. Use user1 for
testing
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            User: ...
        """  # noqa: D205,E501

        response =self.get_user_username_with_http_info(
            username=username,
            **kwargs,
        )
        return User.model_validate_json(response.text)


    def get_user_username_with_http_info(
        self,
        username: str,
        **kwargs: Any,
    ) -> Response:
        """
        Get user by user name..

        Args:
            username(str, required): The name that needs to be fetched. Use user1 for
testing
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})
        
        response = self.api_client.get(
            url=f"/user/{username}",
            headers=headers,
            **kwargs,
        )
        return response

    def put_user_username(
        self,
        user: User, # noqa: E501
        username: str,
        **kwargs: Any,
    ) -> Response:
        """
        Update user resource..

        Args:
            user(User): ...
            username(str, required): name that need to be deleted
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: D205,E501

        response =self.put_user_username_with_http_info(
            username=username,
            user=user, # noqa: E501
            **kwargs,
        )
        return response


    def put_user_username_with_http_info(
        self,
        user: User, # noqa: E501
        username: str,
        **kwargs: Any,
    ) -> Response:
        """
        Update user resource..

        Args:
            user(User): ...
            username(str, required): name that need to be deleted
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})
        
        content = user.model_dump_json(exclude_none=True, by_alias=True) # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.put(
            url=f"/user/{username}",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def delete_user_username(
        self,
        username: str,
        **kwargs: Any,
    ) -> Response:
        """
        Delete user resource..

        Args:
            username(str, required): The name that needs to be deleted
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: D205,E501

        response =self.delete_user_username_with_http_info(
            username=username,
            **kwargs,
        )
        return response


    def delete_user_username_with_http_info(
        self,
        username: str,
        **kwargs: Any,
    ) -> Response:
        """
        Delete user resource..

        Args:
            username(str, required): The name that needs to be deleted
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})
        
        response = self.api_client.delete(
            url=f"/user/{username}",
            headers=headers,
            **kwargs,
        )
        return response