# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 2.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.petstore_service import PetstoreService


@pytest.mark.skip
def test_get_store_order_order_id(petstore_service: PetstoreService):
    order_id = ...

    response = petstore_service.store.get_store_order_order_id(order_id=order_id)
    assert response is not None
