"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: {{ service_name|to_snake_case }}
    version: {{ version }}

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class Status(Enum):
    PLACED = 'placed'
    APPROVED = 'approved'
    DELIVERED = 'delivered'


class Order(BaseModel):
    id: Optional[int] = Field(None, examples=[10])
    pet_id: Optional[int] = Field(None, alias='petId', examples=[198772])
    quantity: Optional[int] = Field(None, examples=[7])
    ship_date: Optional[AwareDatetime] = Field(None, alias='shipDate')
    status: Optional[Status] = Field(
        None, description='Order Status', examples=['approved']
    )
    complete: Optional[bool] = None


class Category(BaseModel):
    id: Optional[int] = Field(None, examples=[1])
    name: Optional[str] = Field(None, examples=['Dogs'])


class User(BaseModel):
    id: Optional[int] = Field(None, examples=[10])
    username: Optional[str] = Field(None, examples=['theUser'])
    first_name: Optional[str] = Field(None, alias='firstName', examples=['John'])
    last_name: Optional[str] = Field(None, alias='lastName', examples=['James'])
    email: Optional[str] = Field(None, examples=['john@email.com'])
    password: Optional[str] = Field(None, examples=['12345'])
    phone: Optional[str] = Field(None, examples=['12345'])
    user_status: Optional[int] = Field(
        None, alias='userStatus', description='User Status', examples=[1]
    )


class Tag(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None


class Status1(Enum):
    AVAILABLE = 'available'
    PENDING = 'pending'
    SOLD = 'sold'


class Pet(BaseModel):
    id: Optional[int] = Field(None, examples=[10])
    name: str = Field(..., examples=['doggie'])
    category: Optional[Category] = None
    photo_urls: List[str] = Field(..., alias='photoUrls')
    tags: Optional[List[Tag]] = None
    status: Optional[Status1] = Field(None, description='pet status in the store')


class ApiResponse(BaseModel):
    code: Optional[int] = None
    type: Optional[str] = None
    message: Optional[str] = None


class FindPetsByStatusResponse200(RootModel[List[Pet]]):
    root: List[Pet]


class FindPetsByTagsResponse200(RootModel[List[Pet]]):
    root: List[Pet]


class UploadFileRequestBody(RootModel[bytes]):
    root: bytes


class GetInventoryResponse200(RootModel[Dict[str, int]]):
    root: Dict[str, int]


class CreateUsersWithListInputRequestBody(RootModel[List[User]]):
    root: List[User]


class LoginUserResponse200(RootModel[str]):
    root: str
