"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: petstore
    version: 2.0.1

    Do not edit the class manually.
"""  # noqa: E501
from internal.clients.http.petstore.apis.pet_api import PetApi
from internal.clients.http.petstore.apis.user_api import UserApi
from internal.clients.http.petstore.apis.store_api import StoreApi

__all__ = [
    "PetApi",
    "UserApi",
    "StoreApi",
]