# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 2.0.1

    You can manually edit this file.
"""  # noqa: E501

from internal.clients.http.petstore.models import *  # noqa: F401, F403
from internal.clients.http.petstore.apis.user_api import UserApi


class UserClient(UserApi):
    """
    You can edit this class manually.

    For override methods see UserApi.
    """
