# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 1.0.0

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.petstore_service import PetstoreService
from internal.clients.http.petstore.models.api_models import (
    CreateUsersWithListInputRequestBody,
)


@pytest.mark.skip
def test_post_user_create_with_list(petstore_service: PetstoreService):
    create_users_with_list_input_request_body = CreateUsersWithListInputRequestBody()

    response = petstore_service.user.post_user_create_with_list(
        create_users_with_list_input_request_body=create_users_with_list_input_request_body
    )
    assert response is not None
