# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 1.0.0

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.petstore_service import PetstoreService


@pytest.mark.skip
def test_get_user_logout(petstore_service: PetstoreService):
    response = petstore_service.user.get_user_logout()
    assert response is not None
