# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 1.0.0

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.petstore_service import PetstoreService
from internal.clients.http.petstore.models.api_models import User


@pytest.mark.skip
def test_post_user(petstore_service: PetstoreService):
    user = User()

    response = petstore_service.user.post_user(user=user)
    assert response is not None
