# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 1.0.0

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.petstore_service import PetstoreService
from internal.clients.http.petstore.models.api_models import User


@pytest.mark.skip
def test_put_user_username(petstore_service: PetstoreService):
    user = User()

    username = ...

    response = petstore_service.user.put_user_username(user=user, username=username)
    assert response is not None
