# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 2.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.petstore_service import PetstoreService


@pytest.mark.skip
def test_delete_user_username(petstore_service: PetstoreService):
    username = ...

    response = petstore_service.user.delete_user_username(username=username)
    assert response is not None
