# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 2.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.petstore_service import PetstoreService


@pytest.mark.skip
def test_post_pet_pet_id(petstore_service: PetstoreService):
    pet_id = ...
    name = ...
    status = ...

    response = petstore_service.pet.post_pet_pet_id(
        pet_id=pet_id, name=name, status=status
    )
    assert response is not None
