# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 2.0.1

    You can manually edit this file.
"""  # noqa: E501

from framework.fixtures.http.petstore_service import PetstoreService
from internal.clients.http.petstore.models.api_models import (
    Pet,
    Tag,
    Status1,
)


def test_post_pet(petstore_service: PetstoreService):
    pet = Pet(
        id=1,
        name="some_pet",
        photoUrls=["some_photo_url"],
        tags=[
            Tag(
                id=0,
                name="string",
            )
        ],
        status=Status1.AVAILABLE,
    )
    response = petstore_service.pet.post_pet(pet=pet)
    assert response is not None
