# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 1.0.0

    You can manually edit this file.
"""  # noqa: E501

from framework.fixtures.http.petstore_service import PetstoreService


# @pytest.mark.skip
def test_delete_pet_pet_id(petstore_service: PetstoreService):
    pet_id = 1
    api_key = 1

    response = petstore_service.pet.delete_pet_pet_id(pet_id=pet_id, api_key=api_key)
    assert response is not None
