# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 2.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.petstore_service import PetstoreService
from internal.clients.http.petstore.models.api_models import (
    UploadFileRequestBody,
)


@pytest.mark.skip
def test_post_pet_pet_id_upload_image(petstore_service: PetstoreService):
    upload_file_request_body = UploadFileRequestBody()

    pet_id = ...
    additional_metadata = ...

    response = petstore_service.pet.post_pet_pet_id_upload_image(
        upload_file_request_body=upload_file_request_body,
        pet_id=pet_id,
        additional_metadata=additional_metadata,
    )
    assert response is not None
