# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: petstore
    version: 1.0.0

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.petstore_service import PetstoreService
from internal.clients.http.petstore.models.api_models import Pet


@pytest.mark.skip
def test_post_pet(petstore_service: PetstoreService):
    pet = Pet()

    response = petstore_service.pet.post_pet(pet=pet)
    assert response is not None
